name: Publish NuGet Package to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x' # Specify the version of .NET SDK to use

    - name: Restore dependencies
      run: dotnet restore src/ApiClient/ApiClient.csproj

    - name: Build the project
      run: dotnet build src/ApiClient/ApiClient.csproj --configuration Release --no-restore

    - name: Pack NuGet package
      run: dotnet pack src/ApiClient/ApiClient.csproj --configuration Release --no-build

    - name: Publish NuGet package to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet nuget push 'src/ApiClient/bin/Release/*.nupkg' --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key $GITHUB_TOKEN
